### ISSUE TITLE
Feature Request: Look into No-Response Github Action

### ISSUE THREAD

**Issue by Unearthlyglow** [Unearthlyglow/micr-ccm#52]
## Summary

[Github Action - NoAction](https://github.com/lee-dohm/no-response?tab=readme-ov-file), looks pretty good to add to the infrastructure of this project as well as future projects. 

## Motivation

I believe this action will help automate some some tasks surrounding ISSUES that need additional info.

**Comment by Unearthlyglow** [comment]
Re-opening. I want to make sure this github Action works before closing this issue. 

Below are the inputs that can be changed in the yml file.  

```yml
inputs:
  closeComment:
    description: Comment to post when closing an Issue for lack of response. Set to `false` to disable.
    default: >
      This issue has been automatically closed because there has been no response
      to our request for more information from the original author. With only the
      information that is currently in the issue, we don't have enough information
      to take action. Please reach out if you have or find the answers we need so
      that we can investigate further.
  daysUntilClose:
    description: Number of days of inactivity before an Issue is closed for lack of response
    default: 14
  responseRequiredColor:
    description: Color for the `responseRequiredLabel`
    default: ffffff
  responseRequiredLabel:
    description: Label indicating that a response from the original author is required
    default: more-information-needed
  token:
    description: Token to access the GitHub API
    required: true
```
