### ISSUE TITLE
Feature Request: DockerFile Update  + How-To Deploy Instructions On DockerHub Instructions

### ISSUE THREAD

**Issue by Unearthlyglow** [Unearthlyglow/micr-ccm#58]
## Summary

- The Dockerfile needs to be updated. Once everything is working with the Dockerfile, we'll need to make sure instructions are written out so people can spin up a container without any issues. 
- I would also like to have all of the fields of the Dockerfile listed out with small explanations with linked documentation. 
For Example:
```YAML
Instruction: FROM gcr.io/distroless/base-debian11 AS build-release-stage
Explanation: "Text Explanation"
Link to Documentation: https://docs.docker.com/language/golang/build-images/

```

I am currently working on ideas over here: https://www.notion.so/capsuleskill/Docker-Setup-1959945c43964c02ab9e65441ae84619

## Motivation

 This will be an alternative solution for people who don't want to use Replit or install the project locally. This will allow users to take the Docker image and, spin up a container and run the program on [Docker Hub](https://hub.docker.com/).

## Describe alternatives you've considered
 Podman: Let's get Docker set up first, then after that, we can explore other options later.

---

<b><div align="center">![CKM Logo!](https://github.com/Unearthlyglow/sveltego/blob/main/images/ckmlogo.png?raw=true)</div>
